import { Vendor } from "@/types/vendor.types";

export const MOCK_VENDORS: Vendor[] = [
  { id: "v1", name: "Riverside Manor", category: "venue", location: "Dhaka", priceFrom: 320000, rating: 4.9, guestCapacity: 300, coverImage: "https://picsum.photos/seed/riverside-manor/600/400", gallery: [], description: "A riverside garden venue with indoor and outdoor halls.", createdAt: "2026-05-01" },
  { id: "v2", name: "Lensfolk Studio", category: "photography", location: "Dhaka", priceFrom: 85000, rating: 4.8, coverImage: "https://picsum.photos/seed/lensfolk-studio/600/400", gallery: [], description: "Documentary-style wedding photography and same-day edits.", createdAt: "2026-05-10" },
  { id: "v3", name: "Rupashi Bridal", category: "bridal", location: "Chattogram", priceFrom: 45000, rating: 5.0, coverImage: "https://picsum.photos/seed/rupashi-bridal/600/400", gallery: [], description: "Bridal makeup and attire styling with trial sessions.", createdAt: "2026-04-20" },
  { id: "v4", name: "Saffron Catering Co.", category: "catering", location: "Dhaka", priceFrom: 60000, rating: 4.7, guestCapacity: 500, coverImage: "https://picsum.photos/seed/saffron-catering/600/400", gallery: [], description: "Traditional and fusion wedding menus with live cooking stations.", createdAt: "2026-05-12" },
  { id: "v5", name: "Petal & Vine Decor", category: "decor", location: "Dhaka", priceFrom: 70000, rating: 4.6, coverImage: "https://picsum.photos/seed/petal-vine/600/400", gallery: [], description: "Floral stage and mandap decor with custom theme design.", createdAt: "2026-05-14" },
  { id: "v6", name: "Emerald Garden Hall", category: "venue", location: "Chattogram", priceFrom: 280000, rating: 4.7, guestCapacity: 250, coverImage: "https://picsum.photos/seed/emerald-garden/600/400", gallery: [], description: "An open-air garden hall with a covered stage.", createdAt: "2026-05-15" },
  { id: "v7", name: "Moonlight Frames", category: "photography", location: "Sylhet", priceFrom: 70000, rating: 4.6, coverImage: "https://picsum.photos/seed/moonlight-frames/600/400", gallery: [], description: "Candid photography and cinematic wedding films.", createdAt: "2026-05-16" },
  { id: "v8", name: "Zarin's Bridal Studio", category: "bridal", location: "Dhaka", priceFrom: 55000, rating: 4.9, coverImage: "https://picsum.photos/seed/zarin-bridal/600/400", gallery: [], description: "Bridal makeup with airbrush techniques and hairstyling.", createdAt: "2026-05-17" },
  { id: "v9", name: "Spice Route Catering", category: "catering", location: "Sylhet", priceFrom: 50000, rating: 4.5, guestCapacity: 400, coverImage: "https://picsum.photos/seed/spice-route/600/400", gallery: [], description: "Regional Bangladeshi cuisine specialists for wedding feasts.", createdAt: "2026-05-18" },
  { id: "v10", name: "Golden Thread Decor", category: "decor", location: "Chattogram", priceFrom: 65000, rating: 4.5, coverImage: "https://picsum.photos/seed/golden-thread/600/400", gallery: [], description: "Elegant drapery, lighting and centerpiece design.", createdAt: "2026-05-19" },
  { id: "v11", name: "The Grand Pavilion", category: "venue", location: "Sylhet", priceFrom: 350000, rating: 4.8, guestCapacity: 400, coverImage: "https://picsum.photos/seed/grand-pavilion/600/400", gallery: [], description: "A grand indoor pavilion with in-house sound and lighting rigs.", createdAt: "2026-05-20" },
  { id: "v12", name: "Aperture Wedding Films", category: "photography", location: "Chattogram", priceFrom: 95000, rating: 4.7, coverImage: "https://picsum.photos/seed/aperture-films/600/400", gallery: [], description: "Full-day photo and videography coverage with drone shots.", createdAt: "2026-05-21" },
  { id: "v13", name: "Noor Bridal Lounge", category: "bridal", location: "Sylhet", priceFrom: 40000, rating: 4.6, coverImage: "https://picsum.photos/seed/noor-bridal/600/400", gallery: [], description: "Affordable bridal packages including mehendi and hair styling.", createdAt: "2026-05-22" },
  { id: "v14", name: "Royal Feast Catering", category: "catering", location: "Chattogram", priceFrom: 72000, rating: 4.8, guestCapacity: 600, coverImage: "https://picsum.photos/seed/royal-feast/600/400", gallery: [], description: "Premium multi-course catering with dedicated event staff.", createdAt: "2026-05-23" },
  { id: "v15", name: "Ivory & Gold Events", category: "decor", location: "Sylhet", priceFrom: 58000, rating: 4.4, coverImage: "https://picsum.photos/seed/ivory-gold/600/400", gallery: [], description: "Minimal, modern decor themes with statement backdrops.", createdAt: "2026-05-24" },
];
